In [2]:
import numpy as np

In [4]:
# 创建示例矩阵
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 进行 SVD 分解
U, S, VT = np.linalg.svd(A)

# 打印结果
print("U矩阵：")
print(U)
print("奇异值（S）：")
print(S)
print("V^T 矩阵：")
print(VT)

U矩阵：
[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
奇异值（S）：
[1.68481034e+01 1.06836951e+00 1.40266540e-16]
V^T 矩阵：
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [ 0.40824829 -0.81649658  0.40824829]]
