In [33]:
import numpy as np

### 1. SVD矩阵分解

在 Python 中，`numpy` 提供了简单的方法来进行 SVD（奇异值分解），可以使用 `numpy.linalg.svd` 函数。SVD 将一个矩阵分解为三个矩阵的乘积：

$$ 
A = U \Sigma V^T 
$$

其中：
- $ A $ 是原始矩阵，
- $ U $ 是一个正交矩阵，包含了左奇异向量，
- $ \Sigma $ 是一个对角矩阵，包含了奇异值，
- $ V^T $ 是 $ V $ 的转置，$ V $ 是另一个正交矩阵，包含了右奇异向量。




In [36]:
# 创建示例矩阵
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 进行 SVD 分解
U, S, VT = np.linalg.svd(A)

print("U矩阵：")
print(U)
print("奇异值（S）：")
print(S)
print("V^T 矩阵：")
print(VT)

U矩阵：
[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
奇异值（S）：
[1.68481034e+01 1.06836951e+00 1.40266540e-16]
V^T 矩阵：
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [ 0.40824829 -0.81649658  0.40824829]]


In [38]:
def svd(data, k):
    U, S, VT = np.linalg.svd(A)
    Sigma_k = np.diag(S[:k])
    U_k = U[:, :k]
    VT_k = VT[:k, :]
    return U, S, VT

### 2. 将SVD用作推荐



$$ 
r = U_{u} \Sigma V_{v}^{\top}
$$

其中：
- $ r $ 是用户 $ u $ 对物品 $ v $ 的评分预测



